apiVersion: apps/v1
kind: Deployment
metadata:
  name: comet-java-app
  namespace: flux-system
  labels:
    app: comet-java-app
  annotations:
    image.toolkit.fluxcd.io/container-image: comet-java-container=971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comet-java-app
  template:
    metadata:
      labels:
        app: comet-java-app
    spec:
      containers:
        - name: comet-java-container
          image: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo:1.0.15 # {"$imagepolicy": "flux-system:comet-app-image-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet: 
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5  
