apiVersion: apps/v1
kind: Deployment
metadata:
  name: comet-java-app
  namespace: flux-system
  labels:
    app: comet-java-app
  annotations:
    image.toolkit.fluxcd.io/container-image: comet-java-container=971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo:1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comet-java-app
  template:
    metadata:
      labels:
        app: comet-java-app
    spec:
      containers:
        - name: comet-java-container
          image: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_ENV
              value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
