apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: java-app-image
  namespace: flux-system
spec:
  interval: 1m
  image: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo

