apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: comet-app-deployment
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/eks/java-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo
      newTag: latest
