apiVersion: v1
kind: Service
metadata:
  name: comet-java-service
  namespace: flux-system
  labels:
    app: comet-java-app
spec:
  type: ClusterIP                 
  ports:
    - port: 8080             
      targetPort: 8080           
  selector:
    app: comet-java-app         
