apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-cred-role
  namespace: flux-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]