apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-cred-rolebinding
  namespace: flux-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flux-system
roleRef:
  kind: Role
  name: ecr-cred-role
  apiGroup: rbac.authorization.k8s.io