apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: comet-app-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: comet-app-repo
  policy:
    tag:
      pattern: "latest"
