apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: comet-app-update-automation
  namespace: flux-system
spec:
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux
        email: ssingh@infotrend.com
      messageTemplate: 'Update image to {{ .ImageRef }}'
    push:
      branch: main
    secretRef:
      name: flux-system
  update:
    path: ./clusters/eks/java-app
    strategy: Setters
