apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: comet-app-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: comet-app-repo
  tag:
    pattern: "latest"
