apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-ecr-credentials
  namespace: flux-system
spec:
  schedule: "0 */12 * * *"
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ecr-token-refresh
              image: bitnami/kubectl:latest # Change image
              command:
                - /bin/sh
                - -c
                - |
                  apt-get update && apt-get install -y awscli # add aws cli
                  TOKEN=$(aws ecr get-login-password --region us-east-1)
                  kubectl create secret docker-registry ecr-reg-cred \
                    --docker-server=971422678337.dkr.ecr.us-east-1.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="$TOKEN" \
                    --namespace=flux-system \
                    --dry-run=client -o yaml | kubectl apply -f -
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_secret_access_key
          restartPolicy: OnFailure