apiVersion: v1
kind: Service
metadata:
  name: comet-react-service
  namespace: flux-system
  labels:
    app: comet-react-app
spec:
  type: ClusterIP  # Use LoadBalancer if you want external access
  ports:
    - port: 3000  # If using Nginx, otherwise 3000
      targetPort: 3000
  selector:
    app: comet-react-app
