apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./java-app
  - ./flux-system

images:
  - name: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo
    newName: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo
    policy:
      semver: ">=1.0.0"

namespace: flux-system
