apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./java-app
  - ./flux-system
  - ./react-app

images:
  - name: 971422678337.dkr.ecr.us-east-1.amazonaws.com/comet-app-repo

namespace: flux-system
